### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by alexmyczko**

### CODE REVIEW

**Comment by auerswal** [comment]
Hi,

thanks for your contribution!

The diff shows that you have started a Debian packaging effort for ssocr, thanks! This changes the outlook on your first pull request.

Please tell me, are you a Debian Developer, and/or do you plan to have your ssocr package included in Debian and/or some derivative distribution? This is important for me to judge the possible impact of your package on the availability of an ssocr package for Debian GNU/Linux and/or derivative distributions without adding third-party package repositories (which might pose trust issues).

I do appreciate your efforts, but I want you to understand my position as well.

Thanks,
Erik

**Comment by auerswal** [comment]
Well, I tried to follow the link to http://sid.ethz.ch/debian/ssocr/ without success (ERR_CONNECTION_TIMED_OUT). I cannot accept the pull request as long as this problem persists. :-(

**Comment by alexmyczko** [comment]
I'll be able to fix that tomorrow.

**Comment by alexmyczko** [comment]
It's fixed now. Well for an official package, we'll need to write an ITP, and fix more things in the package, but I can do that...

Done: http://bugs.debian.org/910646
Uploaded+New Queue: https://ftp-master.debian.org/new/ssocr_2.19.0-1.html

**Comment by auerswal** [comment]
Thanks!

I intend to help your packaging efforts by reading https://wiki.debian.org/UpstreamGuide with the intent to follow the advice given there. Please allow for some time to pass, because I am quite busy in real-life. :-/

BTW do you mind adding a "Homepage: https://www.unix-ag.uni-kl.de/~auerswal/ssocr/" entry to your Debian package? That is the official homepage of ssocr, and there official releases are made. This GitHub project is a copy of my development repository, but ssocr is older than GitHub.

Thanks,
Erik

**Comment by auerswal** [comment]
I have added the link to your .deb package to the ssocr homepage. I do not think they belong inside the README, nor the INSTALL file.

**Pull request closed without merging**
